environment: development
name: ffc-grants-eligibility
namespace: ffc-grants
workstream: ffc-grants
image: ffc-grants-eligibility

labels: {}

appInsights:
  key: not-a-real-key
  
azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-grants-eligibility-config-map

containerSecret:
  name: ffc-grants-eligibility-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000
  messageQueueHost: dummy
  projectDetailsQueueAddress: project-details
  contactDetailsQueueAddress: contact-details
  calculateScoreQueueAddress: calculate-score
  desirabilityScoreSubscriptionAddress: desirability-score-subscription
  desirabilityScoreTopicAddress: desirability-score-topic
  desirabilitySubmittedTopicAddress: desirability-submitted
  redisHostname: redis
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-grants-eligibility

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
