version: '3.8'

services:
  ffc-grants-eligibility:
    build:
      context: .
      target: production
    image: ffc-grants-eligibility
    container_name: ffc-grants-eligibility
    environment: {}
