version: '3.8'

services:
  ffc-grants-eligibility:
    build:
      context: .
      target: production
    image: ffc-grants-eligibility
    container_name: ffc-grants-eligibility
    environment:
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
      TEST_QUEUE_ADDRESS: ${TEST_QUEUE_ADDRESS:-notset}
